CIVIC_SOURCES=[
    {
        "source_key":"gisd_board",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD Board of Trustees",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/board-trustees/board-meetings",
        "allow_domains":["garlandisd.net","www.garlandisd.net","meetings.boardbook.org"],
        "keywords":["agenda","minutes","boardbook","meeting","committee","bond","public forum"],
        "priority":"high",
    },
    {
        "source_key":"gisd_bond",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://garlandisd.net/bond-2023",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["bond","project","committee","facility","construction","campus","timeline"],
        "priority":"high",
    },
    {
        "source_key":"gisd_consolidation",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/campus-consolidation",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["consolidation","campus","transportation","enrollment","boundary","choice","school"],
        "priority":"high",
    },
    {
        "source_key":"gisd_policies",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/policies",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["policy","handbook","code of conduct","student","parental","device","discipline"],
        "priority":"high",
    },
    {
        "source_key":"wylie_isd_board",
        "jurisdiction":"TX-local",
        "governing_body":"Wylie ISD Board of Trustees",
        "kind":"html",
        "root_url":"https://www.wylieisd.net/our-district/school-board/agendas-notices",
        "allow_domains":["wylieisd.net","www.wylieisd.net","meetings.boardbook.org"],
        "keywords":["agenda","minutes","boardbook","meeting","packet","notice"],
        "priority":"normal",
    },
    {
        "source_key":"sachse_civic_archive",
        "jurisdiction":"TX-local",
        "governing_body":"City of Sachse",
        "kind":"html",
        "root_url":"https://www.cityofsachse.com/Archive.aspx",
        "allow_domains":["cityofsachse.com","www.cityofsachse.com"],
        "keywords":[
            "city council","planning and zoning","p&z","agenda","minutes",
            "economic development","edc","municipal development","mdd",
            "tax increment","tirz","public hearing","legal notice",
            "planned development","development report","permit","valuation",
            "resolution","election","quorum notice","impact fee"
        ],
        "priority":"high",
    },
    {
        "source_key":"sachse_planning_zoning",
        "jurisdiction":"TX-local",
        "governing_body":"City of Sachse Planning & Zoning Commission",
        "kind":"html",
        "root_url":"https://www.cityofsachse.com/249/Planning-Zoning-Commission",
        "allow_domains":["cityofsachse.com","www.cityofsachse.com","sachsetx.swagit.com"],
        "keywords":["agenda","minutes","planning","zoning","rezoning","plat","development","ordinance","comprehensive plan","public hearing"],
        "priority":"high",
    },
    {
        "source_key":"dallas_commissioners",
        "jurisdiction":"TX-local",
        "governing_body":"Dallas County Commissioners Court",
        "kind":"html",
        "root_url":"https://www.dallascounty.org/government/comcrt/",
        "allow_domains":["dallascounty.org","www.dallascounty.org"],
        "keywords":["agenda","commissioners court","court order","contract","public hearing","briefing","meeting","official notice","vote"],
        "priority":"high",
    },
    {
        "source_key":"dallas_county_clerk_court",
        "jurisdiction":"TX-local",
        "governing_body":"Dallas County Commissioners Court Clerk",
        "kind":"html",
        "root_url":"https://www.dallascounty.org/government/county-clerk/comm-court-clerk/",
        "allow_domains":["dallascounty.org","www.dallascounty.org"],
        "keywords":["agenda","meeting","notice","court order","contract","vote","commissioners court"],
        "priority":"high",
    },
    {
        "source_key":"dallas_budget",
        "jurisdiction":"TX-local",
        "governing_body":"Dallas County Office of Budget and Evaluation",
        "kind":"html",
        "root_url":"https://www.dallascounty.org/departments/budget/fy2027_budget.php",
        "allow_domains":["dallascounty.org","www.dallascounty.org"],
        "keywords":["budget","tax rate","appropriation","memo","presentation","capital","grant","staffing","revenue","expenditure"],
        "priority":"high",
    },
    {
        "source_key":"collin_commissioners",
        "jurisdiction":"TX-local",
        "governing_body":"Collin County Commissioners Court",
        "kind":"html",
        "root_url":"https://www.collincountytx.gov/Government/Commissioners-Court/agendas",
        "allow_domains":["collincountytx.gov","www.collincountytx.gov","eagenda.collincountytx.gov"],
        "keywords":["agenda","minutes","meeting","commissioners","court","public hearing","order","budget"],
        "priority":"normal",
    },
    {
        "source_key":"wylie_development_projects",
        "jurisdiction":"TX-local",
        "governing_body":"City of Wylie Planning & Zoning / City Council",
        "kind":"arcgis",
        "root_url":"https://gisapp.wylietexas.gov/portalserver/rest/services/Planning/DevelopmentProjects/FeatureServer/80/query",
        "priority":"high",
    },
]
