CIVIC_SOURCES=[
    {
        "source_key":"gisd_board",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD Board of Trustees",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/board-trustees/board-meetings",
        "allow_domains":["garlandisd.net","www.garlandisd.net","meetings.boardbook.org"],
        "keywords":["agenda","minutes","boardbook","meeting","committee","bond","public forum"],
        "priority":"high",
    },
    {
        "source_key":"gisd_bond",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://garlandisd.net/bond-2023",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["bond","project","committee","facility","construction","campus","timeline"],
        "priority":"high",
    },
    {
        "source_key":"gisd_consolidation",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/campus-consolidation",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["consolidation","campus","transportation","enrollment","boundary","choice","school"],
        "priority":"high",
    },
    {
        "source_key":"gisd_policies",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/policies",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["policy","handbook","code of conduct","student","parental","device","discipline"],
        "priority":"high",
    },
    {
        "source_key":"wylie_isd_board",
        "jurisdiction":"TX-local",
        "governing_body":"Wylie ISD Board of Trustees",
        "kind":"html",
        "root_url":"https://www.wylieisd.net/our-district/school-board/agendas-notices",
        "allow_domains":["wylieisd.net","www.wylieisd.net","meetings.boardbook.org"],
        "keywords":["agenda","minutes","boardbook","meeting","packet","notice"],
        "priority":"normal",
    },
    {
        "source_key":"collin_commissioners",
        "jurisdiction":"TX-local",
        "governing_body":"Collin County Commissioners Court",
        "kind":"html",
        "root_url":"https://www.collincountytx.gov/Government/Commissioners-Court/agendas",
        "allow_domains":["collincountytx.gov","www.collincountytx.gov","eagenda.collincountytx.gov"],
        "keywords":["agenda","minutes","meeting","commissioners","court","public hearing","order","budget"],
        "priority":"normal",
    },
    {
        "source_key":"wylie_development_projects",
        "jurisdiction":"TX-local",
        "governing_body":"City of Wylie Planning & Zoning / City Council",
        "kind":"arcgis",
        "root_url":"https://gisapp.wylietexas.gov/portalserver/rest/services/Planning/DevelopmentProjects/FeatureServer/80/query",
        "priority":"high",
    },
]
