CIVIC_SOURCES=[
    {
        "source_key":"gisd_board",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD Board of Trustees",
        "kind":"boardbook",
        "root_url":"https://meetings.boardbook.org/Public/Organization/1084",
        "organization_id":"1084",
        "allow_domains":["meetings.boardbook.org"],
        "priority":"high",
    },
    {
        "source_key":"gisd_bond",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://garlandisd.net/bond-2023",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["bond","project","committee","facility","construction","campus","timeline"],
        "priority":"high",
    },
    {
        "source_key":"gisd_consolidation",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/campus-consolidation",
        "allow_domains":["garlandisd.net","www.garlandisd.net"],
        "keywords":["consolidation","campus","transportation","enrollment","boundary","choice","school"],
        "priority":"high",
    },
    {
        "source_key":"gisd_policies",
        "jurisdiction":"TX-local",
        "governing_body":"Garland ISD",
        "kind":"html",
        "root_url":"https://www.garlandisd.net/about/policies",
        "allow_domains":["garlandisd.net","www.garlandisd.net","pol.tasb.org"],
        "keywords":["policy","handbook","code of conduct","student","parental","device","discipline"],
        "priority":"high",
    },
    {
        "source_key":"wylie_isd_board",
        "jurisdiction":"TX-local",
        "governing_body":"Wylie ISD Board of Trustees",
        "kind":"boardbook",
        "root_url":"https://meetings.boardbook.org/Public/Organization/3480",
        "organization_id":"3480",
        "allow_domains":["meetings.boardbook.org"],
        "priority":"high",
    },
    {
        "source_key":"sachse_council_agendas",
        "jurisdiction":"TX-local",
        "governing_body":"City of Sachse City Council",
        "kind":"civicengage_archive",
        "root_url":"https://www.cityofsachse.com/Archive/65",
        "allow_domains":["cityofsachse.com","www.cityofsachse.com"],
        "priority":"high",
    },
    {
        "source_key":"sachse_council_minutes",
        "jurisdiction":"TX-local",
        "governing_body":"City of Sachse City Council",
        "kind":"civicengage_archive",
        "root_url":"https://www.cityofsachse.com/Archive/66",
        "allow_domains":["cityofsachse.com","www.cityofsachse.com"],
        "priority":"high",
    },
    {
        "source_key":"sachse_pz_agendas",
        "jurisdiction":"TX-local",
        "governing_body":"City of Sachse Planning & Zoning Commission",
        "kind":"civicengage_archive",
        "root_url":"https://www.cityofsachse.com/Archive.aspx?AMID=59",
        "allow_domains":["cityofsachse.com","www.cityofsachse.com"],
        "priority":"high",
    },
    {
        "source_key":"sachse_development_reports",
        "jurisdiction":"TX-local",
        "governing_body":"City of Sachse Development Services",
        "kind":"civicengage_archive",
        "root_url":"https://www.cityofsachse.com/Archive.aspx?AMID=78",
        "allow_domains":["cityofsachse.com","www.cityofsachse.com"],
        "priority":"high",
    },
    {
        "source_key":"dallas_commissioners_notices",
        "jurisdiction":"TX-local",
        "governing_body":"Dallas County Commissioners Court",
        "kind":"dallas_notices",
        "root_url":"https://www.dallascounty.org/government/county-clerk/administration/official-and-legal-notices.php",
        "allow_domains":["dallascounty.org","www.dallascounty.org"],
        "priority":"high",
    },
    {
        "source_key":"dallas_budget",
        "jurisdiction":"TX-local",
        "governing_body":"Dallas County Office of Budget and Evaluation",
        "kind":"html",
        "root_url":"https://www.dallascounty.org/departments/budget/fy2027_budget.php",
        "allow_domains":["dallascounty.org","www.dallascounty.org"],
        "keywords":["budget","tax rate","appropriation","memo","presentation","capital","grant","staffing","revenue","expenditure"],
        "priority":"high",
    },
    {
        "source_key":"collin_commissioners",
        "jurisdiction":"TX-local",
        "governing_body":"Collin County Commissioners Court",
        "kind":"html",
        "root_url":"https://www.collincountytx.gov/Government/Commissioners-Court/agendas",
        "allow_domains":["collincountytx.gov","www.collincountytx.gov","apps2.collincountytx.gov","eagenda.collincountytx.gov"],
        "keywords":["agenda","meeting","notice","commissioners","court","public hearing","order","budget"],
        "priority":"normal",
    },
    {
        "source_key":"wylie_development_projects",
        "jurisdiction":"TX-local",
        "governing_body":"City of Wylie Planning & Zoning / City Council",
        "kind":"arcgis",
        "root_url":"https://gisapp.wylietexas.gov/portalserver/rest/services/Planning/DevelopmentProjects/FeatureServer/80/query",
        "priority":"high",
    },
]
