"""Frozen baseline schema through MVP-16.

Revision ID: 0001
Revises:
"""
from alembic import op
import sqlalchemy as sa

revision="0001"
down_revision=None
branch_labels=None
depends_on=None

def _id():
    return sa.Column("id",sa.Integer(),primary_key=True)

def upgrade():
    op.create_table(
        "bills",_id(),
        sa.Column("jurisdiction",sa.String(32),nullable=False),
        sa.Column("congress",sa.Integer(),nullable=False),
        sa.Column("bill_type",sa.String(16),nullable=False),
        sa.Column("bill_number",sa.String(32),nullable=False),
        sa.Column("title",sa.Text(),nullable=True),
        sa.Column("latest_action",sa.Text(),nullable=True),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("updated_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("jurisdiction","congress","bill_type","bill_number"),
    )
    op.create_table(
        "bill_versions",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("version_code",sa.String(64),nullable=False),
        sa.Column("version_name",sa.Text(),nullable=True),
        sa.Column("source_url",sa.Text(),nullable=True),
        sa.Column("source_system",sa.String(32),nullable=False),
        sa.Column("source_package_id",sa.String(128),nullable=True),
        sa.Column("issued_on",sa.String(32),nullable=True),
        sa.Column("text",sa.Text(),nullable=False),
        sa.Column("sha256",sa.String(64),nullable=False),
        sa.UniqueConstraint("bill_id","version_code","sha256"),
    )
    op.create_table(
        "bill_actions",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("action_date",sa.String(32),nullable=True),
        sa.Column("text",sa.Text(),nullable=False),
        sa.Column("action_code",sa.String(64),nullable=True),
        sa.Column("source_url",sa.Text(),nullable=True),
        sa.Column("raw_json",sa.JSON(),nullable=False),
        sa.UniqueConstraint("bill_id","action_date","text"),
    )
    op.create_table(
        "bill_sponsors",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("bioguide_id",sa.String(32),nullable=True),
        sa.Column("full_name",sa.Text(),nullable=False),
        sa.Column("party",sa.String(16),nullable=True),
        sa.Column("state",sa.String(8),nullable=True),
        sa.Column("district",sa.String(16),nullable=True),
        sa.Column("role",sa.String(24),nullable=False),
        sa.Column("raw_json",sa.JSON(),nullable=False),
        sa.UniqueConstraint("bill_id","bioguide_id","role"),
    )
    op.create_table(
        "amendments",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("amendment_type",sa.String(16),nullable=False),
        sa.Column("amendment_number",sa.String(32),nullable=False),
        sa.Column("congress",sa.Integer(),nullable=False),
        sa.Column("description",sa.Text(),nullable=True),
        sa.Column("latest_action",sa.Text(),nullable=True),
        sa.Column("source_url",sa.Text(),nullable=True),
        sa.Column("raw_json",sa.JSON(),nullable=False),
        sa.UniqueConstraint("congress","amendment_type","amendment_number"),
    )
    op.create_table(
        "sections",_id(),
        sa.Column("version_id",sa.Integer(),sa.ForeignKey("bill_versions.id",ondelete="CASCADE"),nullable=False),
        sa.Column("section_number",sa.String(64),nullable=False),
        sa.Column("heading",sa.Text(),nullable=True),
        sa.Column("text",sa.Text(),nullable=False),
        sa.Column("ordinal",sa.Integer(),nullable=False),
    )
    op.create_table(
        "findings",_id(),
        sa.Column("version_id",sa.Integer(),sa.ForeignKey("bill_versions.id",ondelete="CASCADE"),nullable=False),
        sa.Column("section_id",sa.Integer(),sa.ForeignKey("sections.id",ondelete="CASCADE"),nullable=True),
        sa.Column("kind",sa.String(64),nullable=False),
        sa.Column("severity",sa.Float(),nullable=False),
        sa.Column("label",sa.Text(),nullable=False),
        sa.Column("evidence",sa.Text(),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
    )
    op.create_table(
        "evidence_entities",_id(),
        sa.Column("entity_type",sa.String(32),nullable=False),
        sa.Column("canonical_name",sa.Text(),nullable=False),
        sa.Column("normalized_name",sa.Text(),nullable=False),
        sa.Column("external_ids",sa.JSON(),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.UniqueConstraint("entity_type","normalized_name"),
    )
    op.create_table(
        "legislative_entity_links",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("section_id",sa.Integer(),sa.ForeignKey("sections.id",ondelete="CASCADE"),nullable=True),
        sa.Column("entity_id",sa.Integer(),sa.ForeignKey("evidence_entities.id",ondelete="CASCADE"),nullable=False),
        sa.Column("link_type",sa.String(64),nullable=False),
        sa.Column("evidence",sa.Text(),nullable=False),
        sa.Column("source_url",sa.Text(),nullable=True),
        sa.Column("confidence",sa.Float(),nullable=False),
        sa.Column("extraction_method",sa.String(64),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.UniqueConstraint("bill_id","section_id","entity_id","link_type"),
    )
    op.create_table(
        "entity_relationships",_id(),
        sa.Column("source_entity_id",sa.Integer(),sa.ForeignKey("evidence_entities.id",ondelete="CASCADE"),nullable=False),
        sa.Column("target_entity_id",sa.Integer(),sa.ForeignKey("evidence_entities.id",ondelete="CASCADE"),nullable=False),
        sa.Column("relation_type",sa.String(64),nullable=False),
        sa.Column("evidence",sa.Text(),nullable=False),
        sa.Column("source_url",sa.Text(),nullable=True),
        sa.Column("observed_on",sa.String(32),nullable=True),
        sa.Column("confidence",sa.Float(),nullable=False),
        sa.Column("source_system",sa.String(64),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.UniqueConstraint("source_entity_id","target_entity_id","relation_type","source_url"),
    )
    op.create_table(
        "external_evidence_records",_id(),
        sa.Column("source_system",sa.String(64),nullable=False),
        sa.Column("record_type",sa.String(64),nullable=False),
        sa.Column("external_id",sa.String(160),nullable=False),
        sa.Column("observed_on",sa.String(32),nullable=True),
        sa.Column("source_url",sa.Text(),nullable=True),
        sa.Column("raw_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("source_system","record_type","external_id"),
    )
    op.create_table(
        "correlation_findings",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("legislative_entity_id",sa.Integer(),sa.ForeignKey("evidence_entities.id",ondelete="CASCADE"),nullable=False),
        sa.Column("matched_entity_id",sa.Integer(),sa.ForeignKey("evidence_entities.id",ondelete="CASCADE"),nullable=False),
        sa.Column("match_basis",sa.String(32),nullable=False),
        sa.Column("confidence",sa.Float(),nullable=False),
        sa.Column("evidence",sa.Text(),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("bill_id","legislative_entity_id","matched_entity_id","match_basis"),
    )
    op.create_table(
        "research_runs",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("status",sa.String(32),nullable=False),
        sa.Column("started_at",sa.DateTime(),nullable=False),
        sa.Column("completed_at",sa.DateTime(),nullable=True),
        sa.Column("summary_json",sa.JSON(),nullable=False),
    )
    op.create_table(
        "research_steps",_id(),
        sa.Column("run_id",sa.Integer(),sa.ForeignKey("research_runs.id",ondelete="CASCADE"),nullable=False),
        sa.Column("entity_id",sa.Integer(),sa.ForeignKey("evidence_entities.id",ondelete="CASCADE"),nullable=True),
        sa.Column("source_system",sa.String(64),nullable=False),
        sa.Column("action",sa.String(64),nullable=False),
        sa.Column("status",sa.String(32),nullable=False),
        sa.Column("reason",sa.Text(),nullable=False),
        sa.Column("result_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
    )
    op.create_table(
        "investigation_reports",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("research_run_id",sa.Integer(),sa.ForeignKey("research_runs.id",ondelete="SET NULL"),nullable=True),
        sa.Column("status",sa.String(32),nullable=False),
        sa.Column("report_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
    )
    op.create_table(
        "watch_rules",_id(),
        sa.Column("name",sa.Text(),nullable=False),
        sa.Column("target_type",sa.String(32),nullable=False),
        sa.Column("jurisdiction",sa.String(32),nullable=False),
        sa.Column("congress",sa.Integer(),nullable=True),
        sa.Column("bill_type",sa.String(16),nullable=True),
        sa.Column("bill_number",sa.String(32),nullable=True),
        sa.Column("active",sa.Boolean(),nullable=False),
        sa.Column("auto_research",sa.Boolean(),nullable=False),
        sa.Column("auto_report",sa.Boolean(),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.Column("last_scanned_at",sa.DateTime(),nullable=True),
    )
    op.create_table(
        "watch_scans",_id(),
        sa.Column("watch_rule_id",sa.Integer(),sa.ForeignKey("watch_rules.id",ondelete="CASCADE"),nullable=False),
        sa.Column("status",sa.String(32),nullable=False),
        sa.Column("started_at",sa.DateTime(),nullable=False),
        sa.Column("completed_at",sa.DateTime(),nullable=True),
        sa.Column("summary_json",sa.JSON(),nullable=False),
    )
    op.create_table(
        "watch_events",_id(),
        sa.Column("watch_rule_id",sa.Integer(),sa.ForeignKey("watch_rules.id",ondelete="CASCADE"),nullable=False),
        sa.Column("watch_scan_id",sa.Integer(),sa.ForeignKey("watch_scans.id",ondelete="CASCADE"),nullable=False),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=True),
        sa.Column("event_type",sa.String(64),nullable=False),
        sa.Column("event_key",sa.String(200),nullable=False),
        sa.Column("title",sa.Text(),nullable=False),
        sa.Column("detail_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("watch_rule_id","event_type","event_key"),
    )
    op.create_table(
        "legislative_documents",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("document_type",sa.String(64),nullable=False),
        sa.Column("description",sa.Text(),nullable=True),
        sa.Column("source_url",sa.Text(),nullable=False),
        sa.Column("source_system",sa.String(64),nullable=False),
        sa.Column("issued_on",sa.String(32),nullable=True),
        sa.Column("format",sa.String(32),nullable=False),
        sa.Column("text",sa.Text(),nullable=True),
        sa.Column("sha256",sa.String(64),nullable=True),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("bill_id","document_type","source_url"),
    )
    op.create_table(
        "comparative_findings",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("document_id",sa.Integer(),sa.ForeignKey("legislative_documents.id",ondelete="CASCADE"),nullable=True),
        sa.Column("category",sa.String(64),nullable=False),
        sa.Column("confidence",sa.Float(),nullable=False),
        sa.Column("statement",sa.Text(),nullable=False),
        sa.Column("evidence",sa.Text(),nullable=False),
        sa.Column("source_kind",sa.String(32),nullable=False),
        sa.Column("evidence_hash",sa.String(64),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("bill_id","document_id","category","evidence_hash"),
    )
    op.create_table(
        "provision_lineage",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("section_number",sa.String(64),nullable=False),
        sa.Column("from_version_id",sa.Integer(),sa.ForeignKey("bill_versions.id",ondelete="CASCADE"),nullable=True),
        sa.Column("to_version_id",sa.Integer(),sa.ForeignKey("bill_versions.id",ondelete="CASCADE"),nullable=False),
        sa.Column("event_type",sa.String(32),nullable=False),
        sa.Column("similarity",sa.Float(),nullable=True),
        sa.Column("old_text",sa.Text(),nullable=True),
        sa.Column("new_text",sa.Text(),nullable=True),
        sa.Column("diff_text",sa.Text(),nullable=True),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("bill_id","section_number","from_version_id","to_version_id","event_type"),
    )
    op.create_table(
        "amendment_attributions",_id(),
        sa.Column("lineage_id",sa.Integer(),sa.ForeignKey("provision_lineage.id",ondelete="CASCADE"),nullable=False),
        sa.Column("amendment_id",sa.Integer(),sa.ForeignKey("amendments.id",ondelete="CASCADE"),nullable=False),
        sa.Column("attribution_type",sa.String(32),nullable=False),
        sa.Column("confidence",sa.Float(),nullable=False),
        sa.Column("evidence",sa.Text(),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("lineage_id","amendment_id","attribution_type"),
    )
    op.create_table(
        "scope_findings",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("version_id",sa.Integer(),sa.ForeignKey("bill_versions.id",ondelete="CASCADE"),nullable=False),
        sa.Column("section_id",sa.Integer(),sa.ForeignKey("sections.id",ondelete="CASCADE"),nullable=False),
        sa.Column("category",sa.String(64),nullable=False),
        sa.Column("confidence",sa.Float(),nullable=False),
        sa.Column("anchor_similarity",sa.Float(),nullable=True),
        sa.Column("peer_similarity",sa.Float(),nullable=True),
        sa.Column("statement",sa.Text(),nullable=False),
        sa.Column("evidence",sa.Text(),nullable=False),
        sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("bill_id","version_id","section_id","category"),
    )
    op.create_table(
        "provision_evidence_packets",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("version_id",sa.Integer(),sa.ForeignKey("bill_versions.id",ondelete="CASCADE"),nullable=False),
        sa.Column("section_id",sa.Integer(),sa.ForeignKey("sections.id",ondelete="CASCADE"),nullable=False),
        sa.Column("packet_hash",sa.String(64),nullable=False),
        sa.Column("packet_json",sa.JSON(),nullable=False),
        sa.Column("narrative",sa.Text(),nullable=True),
        sa.Column("llm_model",sa.String(128),nullable=True),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("bill_id","version_id","section_id","packet_hash"),
    )
    op.create_table(
        "investigation_queue_items",_id(),
        sa.Column("bill_id",sa.Integer(),sa.ForeignKey("bills.id",ondelete="CASCADE"),nullable=False),
        sa.Column("version_id",sa.Integer(),sa.ForeignKey("bill_versions.id",ondelete="CASCADE"),nullable=False),
        sa.Column("section_id",sa.Integer(),sa.ForeignKey("sections.id",ondelete="CASCADE"),nullable=False),
        sa.Column("packet_id",sa.Integer(),sa.ForeignKey("provision_evidence_packets.id",ondelete="CASCADE"),nullable=False),
        sa.Column("packet_hash",sa.String(64),nullable=False),
        sa.Column("status",sa.String(32),nullable=False),
        sa.Column("trigger_types",sa.JSON(),nullable=False),
        sa.Column("evidence_coverage",sa.JSON(),nullable=False),
        sa.Column("unresolved_gaps",sa.JSON(),nullable=False),
        sa.Column("analyst_notes",sa.Text(),nullable=True),
        sa.Column("created_at",sa.DateTime(),nullable=False),
        sa.Column("updated_at",sa.DateTime(),nullable=False),
        sa.Column("last_seen_at",sa.DateTime(),nullable=False),
        sa.UniqueConstraint("bill_id","version_id","section_id","packet_hash"),
    )

def downgrade():
    for table in [
        "investigation_queue_items","provision_evidence_packets","scope_findings",
        "amendment_attributions","provision_lineage","comparative_findings",
        "legislative_documents","watch_events","watch_scans","watch_rules",
        "investigation_reports","research_steps","research_runs","correlation_findings",
        "external_evidence_records","entity_relationships","legislative_entity_links",
        "evidence_entities","findings","sections","amendments","bill_sponsors",
        "bill_actions","bill_versions","bills",
    ]:
        op.drop_table(table)
